balad/urls.py
# Define urlpatterns in project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

# from web.views import handler404

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("web.urls", namespace="web")),
        path("", include("order.urls", namespace="order")),
        path("main/", include("main.urls", namespace="main")),
        path("product/", include("products.urls", namespace="product")),
        path("accounts/", include("accounts.urls", namespace="accounts")),
        path("accounts/", include("registration.backends.simple.urls")),
        path(
            "sitemap.xml",
            TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml"),
        ),
        path(
            "robots.txt",
            TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        ),
        path(
            "OneSignalSDKWorker.js",
            TemplateView.as_view(
                template_name="OneSignalSDKWorker.js", content_type="text/javascript"
            ),
        ),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)
handler404 = "web.views.custom_404"

admin.site.site_header = "balad Administration"
admin.site.site_title = "balad Admin Portal"
admin.site.index_title = "Welcome to balad Admin Portal"

kmtsilks/urls.py
# Define urlpatterns in project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

# from web.views import handler404

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("web.urls", namespace="web")),
        path("", include("order.urls", namespace="order")),
        path("main/", include("main.urls", namespace="main")),
        path("product/", include("products.urls", namespace="product")),
        path("accounts/", include("accounts.urls", namespace="accounts")),
        path("accounts/", include("registration.backends.simple.urls")),
        path(
            "sitemap.xml",
            TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml"),
        ),
        path(
            "robots.txt",
            TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        ),
        path(
            "OneSignalSDKWorker.js",
            TemplateView.as_view(
                template_name="OneSignalSDKWorker.js", content_type="text/javascript"
            ),
        ),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)
handler404 = "web.views.custom_404"

admin.site.site_header = "kmtsilks Administration"
admin.site.site_title = "kmtsilks Admin Portal"
admin.site.index_title = "Welcome to kmtsilks Admin Portal"

main/urls.py
from django.urls import path

from . import views
from .views import LoadSubcategoriesView

app_name = "main"

urlpatterns = [
    path("dashboard/", views.IndexView.as_view(), name="index"),
    path("orders/", views.OrderView.as_view(), name="orders"),
    path(
        "order/<str:order_id>/detail/",
        views.OrderDetailView.as_view(),
        name="order_detail",
    ),
    path(
        "invoice/<str:order_id>/",
        views.InvoiceView.as_view(),
        name="invoice",
    ),
    path("order/update/", views.OrderUpdateView.as_view(), name="order_update"),
    # catgory
    path("categories/", views.CategoryListView.as_view(), name="categories"),
    path(
        "category/create/", views.CategoryCreateView.as_view(), name="category_create"
    ),
    path(
        "category/<str:pk>/update/",
        views.CategoryUpdate.as_view(),
        name="category_update",
    ),
    path(
        "category/<str:pk>/delete/",
        views.CategoryDelete.as_view(),
        name="category_delete",
    ),
    # product
    path("products/", views.ProductListView.as_view(), name="product_list"),
    path("product/create/", views.CreateProductView.as_view(), name="product_create"),
    path("product/<pk>/edit/", views.edit_product, name="product_update"),
    path(
        "product/<str:pk>/delete/", views.ProductDelete.as_view(), name="product_delete"
    ),
    # reviews
    path("reviews/", views.ReviewListView.as_view(), name="review_list"),
    path("review/create/", views.ReviewCreateView.as_view(), name="review_create"),
    path("review/<pk>/edit/", views.ReviewUpdateView.as_view(), name="review_update"),
    path(
        "review/<str:pk>/delete/",
        views.ReviewDeleteView.as_view(),
        name="review_delete",
    ),
    # state
    path("states/", views.StateListView.as_view(), name="states"),
    path("state/create/", views.StateCreateView.as_view(), name="state_create"),
    path(
        "state/<str:pk>/update/", views.StateUpdateView.as_view(), name="state_update"
    ),
    path(
        "state/<str:pk>/delete/", views.StateDeleteView.as_view(), name="state_delete"
    ),
    # district
    path("districts/", views.DistrictListView.as_view(), name="districts"),
    path(
        "district/create/", views.DistrictCreateView.as_view(), name="district_create"
    ),
    path(
        "district/<str:pk>/update/",
        views.DistrictUpdateView.as_view(),
        name="district_update",
    ),
    path(
        "district/<str:pk>/delete/",
        views.DistrictDeleteView.as_view(),
        name="district_delete",
    ),
    # customer
    path("customers/", views.CustomerListView.as_view(), name="customers"),
    # sliders
    path("sliders/", views.SliderListView.as_view(), name="sliders"),
    path("slider/create/", views.SliderCreateView.as_view(), name="slider_create"),
    path(
        "slider/<str:pk>/update/",
        views.SliderUpdateView.as_view(),
        name="slider_update",
    ),
    path(
        "slider/<str:pk>/delete/",
        views.SliderDeleteView.as_view(),
        name="slider_delete",
    ),
    # Shipping Fee
    path("shippingfees/", views.ShippingListView.as_view(), name="shippingfees"),
    path(
        "shippingfee/create/",
        views.ShippingCreateView.as_view(),
        name="shippingfee_create",
    ),
    path(
        "shippingfee/<str:pk>/update/",
        views.ShippingUpdateView.as_view(),
        name="shippingfee_update",
    ),
    path(
        "shippingfee/<str:pk>/delete/",
        views.ShippingDeleteView.as_view(),
        name="shippingfee_delete",
    ),
    # Contact
    path("contact/", views.ContactListView.as_view(), name="contacts"),
    path(
        "contact/<str:pk>/delete/",
        views.ContactDeleteView.as_view(),
        name="contact_delete",
    ),
    path(
        "contact/<str:pk>/update/",
        views.ContactUpdateView.as_view(),
        name="contact_update",
    ),
    path("contact/create/", views.ContactCreateView.as_view(), name="contact_create"),
    # testimonial
    path("testimonials/", views.TestimonialListView.as_view(), name="testimonials"),
    path(
        "testimonial/create/",
        views.TestimonialCreateView.as_view(),
        name="testimonial_create",
    ),
    path(
        "testimonial/<str:pk>/update/",
        views.TestimonialUpdateView.as_view(),
        name="testimonial_update",
    ),
    path(
        "testimonial/<str:pk>/delete/",
        views.TestimonialDeleteView.as_view(),
        name="testimonial_delete",
    ),
    # blog
    path("blogs/", views.BlogListView.as_view(), name="blogs"),
    path(
        "blog/create/",
        views.BlogCreateView.as_view(),
        name="blog_create",
    ),
    path(
        "blog/<str:pk>/update/",
        views.BlogUpdateView.as_view(),
        name="blog_update",
    ),
    path(
        "blog/<str:pk>/delete/",
        views.BlogDeleteView.as_view(),
        name="blog_delete",
    ),
    
    # FAQ
    path("faqs/", views.FAQListView.as_view(), name="faqs"),
    path(
        "faq/create/",
        views.FAQCreateView.as_view(),
        name="faq_create",
    ),
    path(
        "faq/<str:pk>/update/",
        views.FAQUpdateView.as_view(),
        name="faq_update",
    ),
    path(
        "faq/<str:pk>/delete/",
        views.FAQDeleteView.as_view(),
        name="faq_delete",
    ),
    # subcategory
    # catgory
    path("subcategories/", views.SubCategoryListView.as_view(), name="sub_categories"),
    path(
        "subcategory/create/",
        views.SubCategoryCreateView.as_view(),
        name="sub_category_create",
    ),
    path(
        "subcategory/<str:pk>/update/",
        views.SubCategoryUpdate.as_view(),
        name="sub_category_update",
    ),
    path(
        "subcategory/<str:pk>/delete/",
        views.SubCategoryDelete.as_view(),
        name="sub_category_delete",
    ),
    # # wedding
    # path("wedding/", views.WeddingListView.as_view(), name="wedding"),
    # path("wedding/create/", views.WeddingCreateView.as_view(), name="wedding_create"),
    # path(
    #     "wedding/<str:pk>/update/",
    #     views.WeddingUpdateView.as_view(),
    #     name="wedding_update",
    # ),
    # path(
    #     "wedding/<str:pk>/delete/",
    #     views.WeddingDeleteView.as_view(),
    #     name="wedding_delete",
    # ),
    # Brands
    path("brands/", views.BrandsListView.as_view(), name="brands"),
    path("brands/create/", views.BrandsCreateView.as_view(), name="brands_create"),
    path(
        "brands/<str:pk>/update/",
        views.BrandsUpdateView.as_view(),
        name="brands_update",
    ),
    path(
        "brands/<str:pk>/delete/",
        views.BrandsDeleteView.as_view(),
        name="brands_delete",
    ),
    path(
        "load-subcategories/",
        LoadSubcategoriesView.as_view(),
        name="load_subcategories",
    ),
]

web/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .views import (SubCategoryAutocomplete, get_images_by_color,
                    quick_add_modal)

app_name = "web"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("blog/", views.BlogView.as_view(), name="blog"),
    path("blog/<slug:slug>/", views.BlogDetailView.as_view(), name="blog_detail"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path(
        "privacy-policy/",
        TemplateView.as_view(template_name="web/privacy_policy.html"),
        name="privacy_policy",
    ),
    path(
        "terms-conditions/",
        TemplateView.as_view(template_name="web/terms_conditions.html"),
        name="terms_conditions",
    ),
    path(
        "refund-policy/",
        TemplateView.as_view(template_name="web/refund_policy.html"),
        name="refund_policy",
    ),
    path(
        "shipping-policy/",
        TemplateView.as_view(template_name="web/shipping_policy.html"),
        name="shipping_policy",
    ),
    path(
        "contact-policy/",
        TemplateView.as_view(template_name="web/contact_policy.html"),
        name="contact_policy",
    ),
    path("shop/", views.ShopView.as_view(), name="shop"),
    path(
        "product-detail/<slug:slug>/",
        views.ProductDetailView.as_view(),
        name="product_detail",
    ),
    path("whatsapp-order/", views.order, name="order"),
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
    path("get_shipping_fee/", views.get_shipping_fee, name="get_shipping_fee"),
    path("shop/cart/", views.cart_view, name="cart"),
    path("shop/cart/add/", views.cart_add, name="add_cart"),
    # path('cart/add/', views.add_to_cart, name='add_to_cart'),
    path(
        "shop/cart-item-clear/<str:item_id>/",
        views.clear_cart_item,
        name="clear_cart_item",
    ),
    path("shop/cart-minus/", views.minus_to_cart, name="minus_to_cart"),
    path("shop/cart-clear/", views.clear_cart, name="clear_cart"),
    # payment
    path("payment/<str:pk>/", views.PaymentView.as_view(), name="payment"),
    path("callback/<str:pk>/", views.callback, name="callback"),
    path(
        "complete-order/<str:pk>/",
        views.CompleteOrderView.as_view(),
        name="complete_order",
    ),
    path(
        "user/order/<str:order_id>/detail/",
        views.UserOrderDetailView.as_view(),
        name="order_detail",
    ),
    # path('my-account/',views.MyAccountView.as_view() ,name='my-account'),
    path("my-orders/", views.MyOrderView.as_view(), name="my_orders"),
    # path('order-details/<int:pk>/',views.MyOrderDetailsView.as_view() ,name='order_detail'),
    path(
        "search-autocomplete/",
        views.AutocompleteView.as_view(),
        name="search-autocomplete",
    ),
    path("error/", views.error, name="error"),
    path("product/search/", views.search_product, name="search"),
    path("account/my-orders-list/", views.my_account_orders, name="my_account_orders"),
    path("category/<slug:slug>/", views.category_list, name="category_product"),
    path(
        "product/<int:pk>/images/", get_images_by_color, name="product_images_by_color"
    ),
    path("quick-add/<int:product_id>/", quick_add_modal, name="quick_add_modal"),
    path("get-product-details/", views.get_product_details, name="get_product_details"),
    path("offer_sale/", views.offer_sale, name="offer_sale"),
    path(
        "subcategory-autocomplete/",
        SubCategoryAutocomplete.as_view(),
        name="subcategory-autocomplete",
    ),
    path("wedding/<slug:slug>/", views.wedding_list, name="wedding"),
    path("product/search/",views.search_product,name='search'),
]

web/models.py
from django.db import models
from tinymce.models import HTMLField
from django.urls import reverse_lazy

# Create your models here.


class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.CharField(
        max_length=15,
    )
    subject = models.CharField(
        max_length=120,
    )
    message = models.TextField()
    timestamp = models.DateTimeField(db_index=True, auto_now_add=True)

    def get_list_url():
        return reverse_lazy("main:contacts")

    def get_update_url(self):
        return reverse_lazy("main:contact_update", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse_lazy("main:contact_delete", kwargs={"pk": self.pk})

    def __str__(self):
        return self.name


class Testimonial(models.Model):
    name = models.CharField(max_length=50)
    position = models.CharField(max_length=120)
    description = models.TextField()
    timestamp = models.DateTimeField(db_index=True, auto_now_add=True)

    def get_list_url():
        return reverse_lazy("main:testimonials")

    def get_update_url(self):
        return reverse_lazy("main:testimonial_update", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse_lazy("main:testimonial_delete", kwargs={"pk": self.pk})

    def __str__(self):
        return str(self.name)


class CustomOrder(models.Model):
    product_name = models.CharField(max_length=100, blank=True)
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    email = models.EmailField()
    address = models.TextField()

    front_neck_depth = models.DecimalField(max_digits=5, decimal_places=2)
    back_neck_depth = models.DecimalField(max_digits=5, decimal_places=2)
    bust = models.DecimalField(max_digits=5, decimal_places=2)
    waist = models.DecimalField(max_digits=5, decimal_places=2)
    sleeve_length = models.DecimalField(max_digits=5, decimal_places=2)
    shoulder_length = models.DecimalField(max_digits=5, decimal_places=2)
    full_length = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.name


class FAQ(models.Model):
    question = models.CharField(max_length=100)
    answer = models.TextField()

    def __str__(self):
        return self.question
    
    class Meta:
        verbose_name = 'FAQ'
        verbose_name_plural = 'FAQs'
    

class Blog(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    meta_title = models.CharField(max_length=170, blank=True, null=True)
    meta_keywords = models.CharField(max_length=170, blank=True, null=True)
    meta_description = models.CharField(max_length=170, blank=True, null=True)
    auther = models.CharField(max_length=100, default="Admin")   
    date = models.DateField()
    image = models.ImageField(upload_to='blog/')
    description = HTMLField()
    
    def get_absolute_url(self):
        return reverse_lazy("web:blog_detail", kwargs={"slug": self.slug})
    
    def get_list_url():
        return reverse_lazy("main:blogs")

    def get_update_url(self):
        return reverse_lazy("main:blog_update", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse_lazy("main:blog_delete", kwargs={"pk": self.pk})
    
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'Blog'
        verbose_name_plural = 'Blogs'
    

templates/dashboard/testimonial/entry.html
{% extends 'dashboard/base.html' %} 
{% load static %} 
{% block title %}{{title}}{% endblock%} 
{% block content %}
<div class="row mb-8">
  <div class="col-md-12">
    <div class="d-md-flex justify-content-between align-items-center">
      <div>
        <h2 class="m-0">{{title}}</h2>
      </div>
      <div class="mt-5 mt-md-0">
        <a onclick="history.back()" class="btn btn-light">Back to Testimonial</a>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-12 col-12">
    <div class="card mb-6 card-lg">
      <div class="card-body p-6 ">
        <form method="POST" enctype="multipart/form-data" class="ajax redirect" data-redirect="{% url 'main:testimonials' %}">
          {% csrf_token %}
          {% comment %} <h4 class="mb-5 h5">Testimonial Image </h4>
          <div class="mb-4 d-flex">
            <div class="position-relative" >
              {% if is_edit %}
              <img class="image  icon-shape icon-xxxl bg-light rounded-4" src="{{slider.image.url}}" alt="Image">
              {% else %}
              <img class="image  icon-shape icon-xxxl bg-light rounded-4" src="{% static 'assets/images/assets/upload.png' %}" alt="Image">
              {% endif %}
              <div class="file-upload position-absolute end-0 top-0 mt-n2 me-n1">
                <input type="file" class="file-input " name="image">
                <span class="icon-shape icon-sm rounded-circle bg-white">
                <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-pencil-fill text-muted" viewBox="0 0 16 16">
                    <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
                  </svg>
                </span>
              </div>
            </div>
          </div> {% endcomment %}
          {% if form.image.help_text %}
            <span class="text-danger">{{form.image.help_text}}</span>
          {% endif %}
          <div class="mt-2 row">
            <!-- input -->
            <div class="mb-3 col-lg-5">
              <label class="form-label">{{form.name.label}} {% if form.name.field.required %}<span class="text-danger">*</span>{% endif %} </label>
              {{ form.name }}
            </div>
            <div class="mb-3 col-lg-4">
              <label class="form-label">{{form.position.label}} {% if form.position.field.required %}<span class="text-danger">*</span>{% endif %}</label>
              {{form.position}}
            </div>
          
            <div class="mb-3">
                <label class="form-label">Description</label>
                {{form.description}}
              </div>
            <div class="col-lg-12">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block js_plugins %}
{% include 'web/includes/form-ajax.html' %}
<script>
  $(document).ready(function () {
    // Function to update the slug based on the name
    function updateSlug() {
        var name = $('#id_name').val();
        var slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
        $('#id_slug').val(slug);
    }

    // Attach the function to the change event of the name field
    $('#id_name').on('input', updateSlug);
});
</script>
{% endblock %}

templates/dashboard/testimonial/list.html
{% extends 'dashboard/base.html' %} 
{% load static %} 
{% block title %}Testimonials{% endblock%} 
{% block content %}
<div class="row mb-8">
    <div class="col-md-12">
      <!-- page header -->
      <div class="d-md-flex justify-content-between align-items-center">
        <div>
          <h2 class="m-0">Testimonials</h2>
        </div>
        <!-- button -->
        <div>
          <a href="{% url 'main:testimonial_create' %}" class="btn btn-primary">Add Testimonial</a>
        </div>
      </div>
    </div>
  </div>
  <!-- row -->
  <div class="row ">
    <div class="col-xl-12 col-12 mb-5">
      <!-- card -->
      <div class="card h-100 card-lg">
        <!-- card body -->
        <div class="card-body p-0">
          <!-- table -->
          <div class="table-responsive">
            <table id="myTable" class="table myTable table-centered table-hover text-nowrap table-borderless mb-0 table-with-checkbox">
              <thead class="bg-light">
                <tr>
                  <th>#</th> 
                  <th>name</th>
                  <th>position</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {% for testimonial in testimonial_list %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                 
                  <td><a href="{{ testimonial.get_absolute_url }}" class="text-reset">{{ testimonial.name }}</a></td>
                  <td>{{ testimonial.position }}</td>
                  
                  <td>
                    <div class="dropdown">
                      <a href="#" class="text-reset" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="feather-icon icon-more-vertical fs-5"></i>
                      </a>
                      <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{testimonial.get_delete_url}}"><i class="bi bi-trash me-3"></i>Delete</a></li>
                        <li><a class="dropdown-item" href="{{testimonial.get_update_url}}"><i class="bi bi-pencil-square me-3 "></i>Edit</a></li>
                      </ul>
                    </div>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block css %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="{% static 'assets/css/dataTable.css' %}{{current_version}}">
{% endblock %}

{% block js %}
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
<script>
  let table = new DataTable('#myTable', {
      responsive: true
  });
</script>

{% endblock  %}