balad/urls.py
# Define urlpatterns in project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

# from web.views import handler404

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("web.urls", namespace="web")),
        path("", include("order.urls", namespace="order")),
        path("main/", include("main.urls", namespace="main")),
        path("product/", include("products.urls", namespace="product")),
        path("accounts/", include("accounts.urls", namespace="accounts")),
        path("accounts/", include("registration.backends.simple.urls")),
        path(
            "sitemap.xml",
            TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml"),
        ),
        path(
            "robots.txt",
            TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        ),
        path(
            "OneSignalSDKWorker.js",
            TemplateView.as_view(
                template_name="OneSignalSDKWorker.js", content_type="text/javascript"
            ),
        ),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)
handler404 = "web.views.custom_404"

admin.site.site_header = "balad Administration"
admin.site.site_title = "balad Admin Portal"
admin.site.index_title = "Welcome to balad Admin Portal"

kmtsilks/urls.py
# Define urlpatterns in project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

# from web.views import handler404

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("web.urls", namespace="web")),
        path("", include("order.urls", namespace="order")),
        path("main/", include("main.urls", namespace="main")),
        path("product/", include("products.urls", namespace="product")),
        path("accounts/", include("accounts.urls", namespace="accounts")),
        path("accounts/", include("registration.backends.simple.urls")),
        path(
            "sitemap.xml",
            TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml"),
        ),
        path(
            "robots.txt",
            TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        ),
        path(
            "OneSignalSDKWorker.js",
            TemplateView.as_view(
                template_name="OneSignalSDKWorker.js", content_type="text/javascript"
            ),
        ),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)
handler404 = "web.views.custom_404"

admin.site.site_header = "kmtsilks Administration"
admin.site.site_title = "kmtsilks Admin Portal"
admin.site.index_title = "Welcome to kmtsilks Admin Portal"

order/urls.py
app_name = "order"

urlpatterns = []

web/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .views import (SubCategoryAutocomplete, get_images_by_color,
                    quick_add_modal)

app_name = "web"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("blog/", views.BlogView.as_view(), name="blog"),
    path("blog/<slug:slug>/", views.BlogDetailView.as_view(), name="blog_detail"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path(
        "privacy-policy/",
        TemplateView.as_view(template_name="web/privacy_policy.html"),
        name="privacy_policy",
    ),
    path(
        "terms-conditions/",
        TemplateView.as_view(template_name="web/terms_conditions.html"),
        name="terms_conditions",
    ),
    path(
        "refund-policy/",
        TemplateView.as_view(template_name="web/refund_policy.html"),
        name="refund_policy",
    ),
    path(
        "shipping-policy/",
        TemplateView.as_view(template_name="web/shipping_policy.html"),
        name="shipping_policy",
    ),
    path(
        "contact-policy/",
        TemplateView.as_view(template_name="web/contact_policy.html"),
        name="contact_policy",
    ),
    path("shop/", views.ShopView.as_view(), name="shop"),
    path(
        "product-detail/<slug:slug>/",
        views.ProductDetailView.as_view(),
        name="product_detail",
    ),
    path("whatsapp-order/", views.order, name="order"),
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
    path("get_shipping_fee/", views.get_shipping_fee, name="get_shipping_fee"),
    path("shop/cart/", views.cart_view, name="cart"),
    path("shop/cart/add/", views.cart_add, name="add_cart"),
    # path('cart/add/', views.add_to_cart, name='add_to_cart'),
    path(
        "shop/cart-item-clear/<str:item_id>/",
        views.clear_cart_item,
        name="clear_cart_item",
    ),
    path("shop/cart-minus/", views.minus_to_cart, name="minus_to_cart"),
    path("shop/cart-clear/", views.clear_cart, name="clear_cart"),
    # payment
    path("payment/<str:pk>/", views.PaymentView.as_view(), name="payment"),
    path("callback/<str:pk>/", views.callback, name="callback"),
    path(
        "complete-order/<str:pk>/",
        views.CompleteOrderView.as_view(),
        name="complete_order",
    ),
    path(
        "user/order/<str:order_id>/detail/",
        views.UserOrderDetailView.as_view(),
        name="order_detail",
    ),
    # path('my-account/',views.MyAccountView.as_view() ,name='my-account'),
    path("my-orders/", views.MyOrderView.as_view(), name="my_orders"),
    # path('order-details/<int:pk>/',views.MyOrderDetailsView.as_view() ,name='order_detail'),
    path(
        "search-autocomplete/",
        views.AutocompleteView.as_view(),
        name="search-autocomplete",
    ),
    path("error/", views.error, name="error"),
    path("product/search/", views.search_product, name="search"),
    path("account/my-orders-list/", views.my_account_orders, name="my_account_orders"),
    path("category/<slug:slug>/", views.category_list, name="category_product"),
    path(
        "product/<int:pk>/images/", get_images_by_color, name="product_images_by_color"
    ),
    path("quick-add/<int:product_id>/", quick_add_modal, name="quick_add_modal"),
    path("get-product-details/", views.get_product_details, name="get_product_details"),
    path("offer_sale/", views.offer_sale, name="offer_sale"),
    path(
        "subcategory-autocomplete/",
        SubCategoryAutocomplete.as_view(),
        name="subcategory-autocomplete",
    ),
    path("wedding/<slug:slug>/", views.wedding_list, name="wedding"),
    path("product/search/",views.search_product,name='search'),
]

order/models.py
import uuid

from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from accounts.models import User


def generate_order_id():
    timestamp = timezone.now().strftime("%y%m%d")
    unique_id = uuid.uuid4().hex[:6]
    return f"{timestamp}{unique_id.upper()}"


class Order(models.Model):
    unique_transaction_id = models.UUIDField(
        unique=True, editable=False, blank=True, null=True
    )
    # razorpay_payment_id = models.CharField(max_length=200, blank=True, null=True)
    # razorpay_order_id = models.CharField(max_length=200, blank=True, null=True)
    # razorpay_signature = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(db_index=True, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # payable = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    order_id = models.CharField(max_length=255, default=generate_order_id)
    is_ordered = models.BooleanField(default=False)
    completed_at = models.DateTimeField(blank=True, null=True)
    payment_method = models.CharField(
        max_length=20,
        choices=(("COD", "Cash On Delivery"), ("OP", "Online Payment")),
        default="OP",
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    full_name = models.CharField(max_length=100)
    address_line_1 = models.CharField("Complete Address", max_length=100)
    address_line_2 = models.CharField("Landmark", max_length=100)
    state = models.CharField(max_length=200, null=True)
    district = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=100)
    pin_code = models.IntegerField()
    mobile_no = models.CharField(max_length=15)
    alternative_no = models.CharField(max_length=15, blank=True, null=True)
    email = models.EmailField()

    subtotal = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    service_fee = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    shipping_fee = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    order_status = models.CharField(
        max_length=50,
        default="Pending",
        choices=(
            ("Pending", "Pending"),
            ("Placed", "Order Placed"),
            ("Shipped", "Order Shipped"),
            ("InTransit", "In Transit"),
            ("Delivered", "Order Delivered"),
            ("Cancelled", "Order Cancelled"),
        ),
    )
    payment_status = models.CharField(
        max_length=50,
        default="Pending",
        choices=(
            ("Pending", "Pending"),
            ("Failed", "Failed"),
            ("Success", "Success"),
            ("Cancelled", "Cancelled"),
        ),
    )

    class Meta:
        verbose_name = _("Order")
        verbose_name_plural = _("Orders")
        ordering = ("-id",)

    def get_items(self):
        return OrderItem.objects.filter(order=self)

    # def get_grand_total(self):
    #     total = self.payable + self.service_fee + self.shipping_fee
    #     return total

    def order_total(self):
        return float(sum([item.subtotal for item in self.get_items()]))

    def get_user_absolute_url(self):
        return reverse("web:order_detail", kwargs={"order_id": self.order_id})

    def __str__(self):
        return f"{self.order_id}"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey("products.AvailableSize", on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    quantity = models.PositiveIntegerField(default=1)
    sku = models.CharField(max_length=100, null=True, blank=True)
    color = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        verbose_name = _("Order Item")
        verbose_name_plural = _("Order Items")

    def __str__(self):
        return f"{self.order} - {self.product}"

    def subtotal(self):
        return self.price * self.quantity

order/forms.py
from django import forms

from .models import Order


class OrderForm(forms.ModelForm):
    selected_dial_code_mobile = forms.CharField(
        widget=forms.HiddenInput(), required=False
    )
    selected_dial_code_alternative = forms.CharField(
        widget=forms.HiddenInput(), required=False
    )

    class Meta:
        model = Order
        fields = [
            "full_name",
            "address_line_1",
            "address_line_2",
            "mobile_no",
            "alternative_no",
            "state",
            "district",
            "city",
            "pin_code",
            "email",
        ]
        widgets = {
            "full_name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Full name"}
            ),
            "address_line_1": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "House/Floor No. Building Name or Street, Locality",
                }
            ),
            "address_line_2": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Any nearby post office, market, Hospital as the landmark",
                }
            ),
            "mobile_no": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Mobile No",
                    "type": "tel",
                    "maxlength": "10",
                }
            ),
            "alternative_no": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Alternative Mobile No",
                    "type": "tel",
                    "maxlength": "10",
                }
            ),
            "state": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "State"}
            ),
            "district": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "District"}
            ),
            "city": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "City"}
            ),
            "pin_code": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Pin Code"}
            ),
            "email": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Email", "type": "email"}
            ),
        }

templates/dashboard/order/list.html
{% extends 'dashboard/base.html' %} 
{% load static %} 
{% block title %}Order List{% endblock%} 
{% block content %}
    <!-- row -->
    <div class="row mb-8">
        <div class="col-md-12">
          <!-- page header -->
          <div>
            <h2 class="m-0">Order List</h2>
          </div>
        </div>
      </div>
      <!-- row -->
      <div class="row">
        <div class="col-xl-12 col-12 mb-5">
          <!-- card -->
          <div class="card h-100 card-lg">
            <!-- card body -->
            <div class="card-body p-0">
              <!-- table responsive -->
              <div class="table-responsive">
                <table id="myTable" class="table myTable table-centered table-hover text-nowrap table-borderless mb-0 table-with-checkbox">
                  <thead class="bg-light">
                    <tr>
                      <th>#</th>
                      <th>Order ID</th>
                      <th>Customer</th>
                      <th>Date & TIme</th>
                      {% comment %} <th>Payment</th> {% endcomment %}
                      <th>Status</th>
                      <th>Amount</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for order in order_list %}
                    <tr>
                      <td>{{forloop.counter}}</td>
                      <td><a href="{% url 'main:order_detail' order.order_id %}" class="text-reset">{{ order.order_id }}</a></td>
                      <td>{{ order.full_name }}</td>

                      <td>{{ order.created }}</td>
                      {% comment %} <td>{{ order.get_payment_method_display }}</td> {% endcomment %}
                      <td>
                        {% if order.order_status == 'Delivered' %}
                        <span class="badge bg-light-primary text-dark-primary">{{ order.order_status }}</span>
                        {% elif order.order_status == 'Pending' %}
                        <span class="badge bg-light-warning text-dark-warning">{{ order.order_status }}</span>
                        {% elif order.order_status == 'Shipped' %}
                        <span class="badge bg-light-info text-dark-info">{{ order.order_status }}</span>
                        {% elif order.order_status == 'Cancelled' %}
                        <span class="badge bg-light-danger text-dark-danger">{{ order.order_status }}</span>
                        {% endif %}
                      </td>
                      <td>  {{ order.subtotal }} </td>
                      <td>
                        <div class="dropdown">
                          <a href="#" class="text-reset" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="feather-icon icon-more-vertical fs-5"></i>
                          </a>
                          <ul class="dropdown-menu">
                            <li><a class="dropdown-item action-button " data-status="Pending" data-text="Confirm Order Status Pending" data-id="{{ order.id }}"  href="{% url 'main:order_update' %}"><i class=" me-3"></i>Pending</a></li>
                            <li><a class="dropdown-item action-button " data-status="Shipped" data-text="Confirm Order Status Shipped" data-id="{{ order.id }}" href="{% url 'main:order_update' %}"><i class=" me-3"></i>Shipped</a></li>
                            <li><a class="dropdown-item action-button " data-status="Delivered" data-text="Confirm Order Status Delivered" data-id="{{ order.id }}" href="{% url 'main:order_update' %}"><i class=" me-3 "></i>Delivered</a></li>
                            <li><a class="dropdown-item action-button " data-status="Cancelled" data-text="Confirm Order Status Canceled" data-id="{{ order.id }}" href="{% url 'main:order_update' %}"><i class=" me-3"></i>Canceled</a></li>
                          </ul>
                        </div>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock content %}

{% block css %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9.15.3/dist/sweetalert2.all.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="{% static 'assets/css/dataTable.css' %}{{current_version}}">
{% endblock %}

{% block js %}
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
<script>
    let table = new DataTable('#myTable', {
        responsive: true
    });
</script>
<script>
  $(document).on("click", ".action-button", function (e) {
        e.preventDefault();
        $this = $(this);
        var html = $this.attr("data-text");
        var icon = "question";
        var id = $this.attr("data-id");
        var status = $this.attr("data-status");
        var url = $this.attr("href");
        var title = $this.attr("data-title");
        if (!title) {
            title = "Are you sure?";
        }

        Swal.fire({
            title: title,
            html: html,
            icon: icon,
            showCancelButton: true,
        }).then((result) => {
            if (result.value) {
                window.setTimeout(function () {
                    $.ajax({
                        type: "GET",
                        url: url,
                        dataType: "json",
                        data: { pk: id , status: status},

                        success: function (data) {
                            var message = data.message;
                            var status = data.status;
                            var reload = data.reload;
                            var redirect = data.redirect;
                            var redirect_url = data.redirect_url;
                            var title = data.title;

                            if (status == "true") {
                                title?title=title:title="Success";
                                Swal.fire({title:title,html:message,icon:"success"}).then(function(){"true"==redirect&&(window.location.href=redirect_url),"true"==reload&&window.location.reload()});
                            } else {
                                title?title=title:title="An Error Occurred";
                                Swal.fire({ title: title, html: message, icon: "error" });
                            }
                        },
                        error: function (data) {
                            var title = "An error occurred";
                            var message = "An error occurred. Please try again later.";
                            Swal.fire({ title: title, html: message, icon: "error" });
                        },
                    });
                }, 100);
            } else {
                console.log("action cancelled");
            }
        });
    });
</script>
{% endblock  %}

templates/dashboard/order/single.html
{% extends 'dashboard/base.html' %} 
{% load static %} 
{% block title %}Order View{% endblock%} 
{% block content %}
<div class="row ">
    <div class="col-xl-12 col-12 mb-5">
        <!-- card -->
        <div class="card h-100 card-lg">
            <div class="card-body p-6">
                <div class="d-md-flex justify-content-between">
                    <div class="d-flex align-items-center mb-2 mb-md-0">
                        <h2 class="mb-0">Order ID: {{order.order_id}}</h2>
                        <span class="badge bg-light-warning text-dark-warning ms-2">{{order.status}}</span>
                    </div>
                    <div class="d-md-flex">
                        <div class="ms-md-3">
                          <a href="{% url 'main:invoice' order.order_id %}" class="btn btn-secondary">Download Invoice</a>
                        </div>
                    </div>
                </div>
                <div class="mt-8 row">
                    <div class="col-lg-6 col-md-6 col-12 mb-6">
                        <h6>Shipping Address</h6>
                        <p class="mb-1 lh-lg">{{order.full_name}}<br>
                        {{order.address_line_1}} <br>
                        {{order.address_line_2}} <br>
                        {{order.city}},{{order.district}} <br>
                        Pin Code : {{order.pin_code}} <br>
                        Contact No. {{order.mobile_no}}</p>
                    </div>
                    <!-- address -->
                    <div class="col-lg-6 col-md-6 col-12 mb-6">
                        <h6>Order Details</h6>
                        <p class="mb-1 lh-lg">Order ID: <span class="text-dark">{{order.order_id}}</span><br>
                            Order Date: <span class="text-dark">{{order.created}}</span><br>
                            Order Total: <span class="text-dark">₹{{ order.subtotal }}</span><br>
                            Order Status: <span class="text-dark">{{order.get_order_status_display}}</span><br>
                            {% comment %} Payment Method: <span class="text-dark">{{order.get_payment_method_display}}</span><br> {% endcomment %}
                            Payment Status: <span class="text-dark">{{order.get_payment_status_display}}</span><br>
                        
                        </p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12 table-responsive">
                    <!-- Table -->
                    <table class="table mb-0 text-nowrap table-centered">
                    <!-- Table Head -->
                        <thead class="bg-light">
                            <tr>
                                <th>Products</th>
                                <th>Price</th>
                                <th>Color</th>
                                <th>Quantity</th>
                                <th>Total</th>
                            </tr>
                        </thead>
                        <!-- tbody -->
                        <tbody>
                            {% for i in order.get_items %}
                            <tr>
                                <td>
                                    <a href="{{i.order.get_absolute_url}}" class="text-inherit">
                                        <div class="ms-lg-4 mt-2 mt-lg-0">
                                            <h5 class="mb-0 h6">
                                                {{i.product}}
                                                <br>
                                                ({{i.sku}})
                                            </h5>
                                        </div>
                                    </a>
                                </td>
                                <td><span class="text-body">₹ {{i.price}}</span></td>
                                <td>{{i.color}}</td>
                                <td>{{i.quantity}}</td>
                                <td>₹ {{i.subtotal}}</td>
                            </tr>
                            {% endfor %}
                            <tr>
                                <td class="border-bottom-0 pb-0"></td>
                                <td class="border-bottom-0 pb-0"></td>
                                <td></td>
                                <td colspan="1" class="fw-medium text-dark ">
                                  <!-- text -->
                                  Sub Total :
                                </td>
                                <td class="fw-medium text-dark ">
                                  <!-- text -->
                                  ₹{{ order.subtotal }}
                                </td>
                            </tr>
                            <tr>
                                <td class="border-bottom-0 pb-0"></td>
                                <td class="border-bottom-0 pb-0"></td>
                                {% comment %} <td colspan="1" class="fw-medium text-dark ">
                                  <!-- text -->
                                  Service Cost :
                                </td> {% endcomment %}
                                {% comment %} <td class="fw-medium text-dark ">
                                  ₹{{order.service_fee}}
                                </td> {% endcomment %}
                            </tr>
                            <tr>
                                <td class="border-bottom-0 pb-0"></td>
                                <td class="border-bottom-0 pb-0"></td>
                                <td></td>
                                <td colspan="1" class="fw-medium text-dark ">
                                  <!-- text -->
                                  Shipping Cost :
                                </td>
                                <td class="fw-medium text-dark ">
                                  <!-- text -->
                                  ₹{{order.shipping_fee}}
                                </td>
                            </tr>
                            <tr>
                                <td class="border-bottom-0 pb-0"></td>
                                <td class="border-bottom-0 pb-0"></td>
                                <td></td>
                                <td colspan="1" class="fw-medium text-dark ">
                                  <!-- text -->
                                  Grand Total :
                                </td>
                                <td class="fw-medium text-dark ">
                                  <!-- text -->
                                  ₹{{ order.subtotal }}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}